jobs:
  build:
    machine: # executor type
      image: ubuntu-2204:current # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
      docker_layer_caching: true
    resource_class: jheck90/dance-judging
    working_directory: ~/bender-ci
    steps:
      - checkout          
      - run:
          name: Install Docker
          command: |
            if ! command -v docker &> /dev/null
            then
                curl -fsSL https://get.docker.com -o get-docker.sh
                sh get-docker.sh
            else
                echo "Docker is already installed."
            fi
      - run:
          name: Run tests
          command: |
            echo "Hello from the test step"
      - run:
          name: Build Docker image
          command: |
            docker build .
      - discord/approval:
          webhook: "${DISCORD_WEBHOOK}"

  build_and_push:
    machine: # executor type
      image: ubuntu-2204:current # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
      docker_layer_caching: true
    resource_class: jheck90/dance-judging
    working_directory: ~/bender-ci
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            if ! command -v docker &> /dev/null
            then
                curl -fsSL https://get.docker.com -o get-docker.sh
                sh get-docker.sh
            else
                echo "Docker is already installed."
            fi
      - run:
          name: Run Build
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/bender:$TAG -t $DOCKERHUB_USERNAME/bender:latest .
      - run:
          name: Push application Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/bender --all-tags
      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "${DISCORD_WEBHOOK}"
          success_message: "**${CIRCLE_USERNAME}**'s docker image built. Hello, jheck90/bender:0.1.$CIRCLE_BUILD_NUM"

orbs:
  discord: antonioned/discord@0.1.0
version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      - hold:
          type: approval
          requires:
            - build
      - build_and_push:
          requires:
            - hold
